orders:
- id: e537ce32-5701-42a0-af4d-d4d7bd696347
  symbol: TSLA
  side: buy
  qty: '1'
  order_type: limit
  limit_price: '420'
  external_id: null
  status: filled
- id: 5a27e1bf-6614-4ec3-8752-e5946d585192
  symbol: TSLA
  side: buy
  qty: '102'
  order_type: market
  limit_price: null
  external_id: null
  status: filled
- id: 583653ba-8164-4e2e-b456-b0523354dc9a
  symbol: AAPL
  side: buy
  qty: '5'
  order_type: market
  limit_price: null
  external_id: null
  status: filled
- id: 76d5f0e0-30a8-4684-8f3d-2f06512038ac
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 52e39125-6059-4e09-a7a6-46cf7652ecc0
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: e5543f06-9c91-4f52-8a82-e0a3f5ec02cf
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 637d90f9-3be0-466a-aed8-7dc5617835b9
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: f803771d-daa2-45cb-b590-8d0511f3f71e
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 903de922-4025-4e19-9554-ce93d25a8b03
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 8968cc96-abf8-46d9-8bcf-fca233748a74
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: b50d9c21-daba-4759-8d0c-652efefbe124
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 47d1aeec-73dd-42fe-8d1b-1056c4de9637
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 97fce23a-7911-495a-8200-fbde547208ef
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: ffa0e062-38d3-4f3c-ba81-eaa1ff7989b9
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 6b39ee08-1f81-4b75-826b-3b493db07143
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 8bcb6479-b61d-481e-8992-55414b43904f
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: e47c6e87-5865-41cb-9606-8228165d9fc8
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: b3867d38-823c-4656-9d88-412e986a9837
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 2ab5612c-0d6e-474f-9ac2-945dd4a71460
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: 83329091-e360-4976-9c0b-dffcd4aa1587
  symbol: TSLA
  side: sell
  qty: '12'
  order_type: limit
  limit_price: '416'
  external_id: null
  status: new
- id: b700f02d-3cd5-4b3c-9b43-f96985c0bcf4
  symbol: AAPL
  side: sell
  qty: '5'
  order_type: limit
  limit_price: '261.3'
  external_id: null
  status: new
- id: a2e92b5e-612d-4e29-a27d-ed4c63bc6aee
  symbol: AAPL
  side: sell
  qty: '5'
  order_type: limit
  limit_price: '261.22'
  external_id: null
  status: new
- id: 7a387920-faa6-4649-bff7-12858cc959a4
  symbol: AAPL
  side: sell
  qty: '5'
  order_type: limit
  limit_price: '261.15'
  external_id: null
  status: new
- id: e056d831-c202-4737-ab0a-a2516f4e506e
  symbol: NVDA
  side: buy
  qty: '26'
  order_type: limit
  limit_price: '189.61'
  external_id: null
  status: new
- id: 41553769-0d52-478b-be04-7d30a41dde48
  symbol: NVDA
  side: buy
  qty: '26'
  order_type: limit
  limit_price: '189.61'
  external_id: null
  status: new
- id: b83a391c-fb4b-4ce1-94ca-51047a042e5d
  symbol: MSFT
  side: buy
  qty: '12'
  order_type: limit
  limit_price: '404.44'
  external_id: null
  status: new
- id: 96067883-ff62-4ec4-a517-d2c5dee8e310
  symbol: MSFT
  side: buy
  qty: '12'
  order_type: limit
  limit_price: '404.44'
  external_id: null
  status: new
- id: e57e17cd-a227-4e5d-8013-841d154bd32e
  symbol: XLK
  side: buy
  qty: '35'
  order_type: limit
  limit_price: '139.63'
  external_id: null
  status: new
- id: 57a2e0f9-e42d-443a-bb09-cdd7e08c7bc3
  symbol: XLK
  side: buy
  qty: '35'
  order_type: limit
  limit_price: '139.63'
  external_id: null
  status: new
- id: b62e550b-81ad-4dad-8602-b5c2666e15a7
  symbol: GOOGL
  side: buy
  qty: '15'
  order_type: limit
  limit_price: '313.87'
  external_id: null
  status: new
- id: fc117fcf-5ee7-47e8-a785-399510369bd8
  symbol: GOOGL
  side: buy
  qty: '15'
  order_type: limit
  limit_price: '313.87'
  external_id: null
  status: new
- id: ce5818e1-fc5d-4e94-a295-3b58ef638214
  symbol: AMZN
  side: buy
  qty: '25'
  order_type: limit
  limit_price: '199.59'
  external_id: null
  status: new
- id: a16e91bf-df33-4fa6-b05f-fe604a37db90
  symbol: AMZN
  side: buy
  qty: '25'
  order_type: limit
  limit_price: '199.59'
  external_id: null
  status: new
- id: a2fd9281-e917-4a70-99d5-a2c8c0d60723
  symbol: XLI
  side: buy
  qty: '28'
  order_type: limit
  limit_price: '172.79'
  external_id: null
  status: new
- id: 3671e42e-42cc-4b95-8ee3-54fbc5ff065f
  symbol: XLF
  side: buy
  qty: '96'
  order_type: limit
  limit_price: '51.57'
  external_id: null
  status: new
- id: 505149e2-7a94-4977-a19c-9c177617f31d
  symbol: XLP
  side: buy
  qty: '55'
  order_type: limit
  limit_price: '89.51'
  external_id: null
  status: new
- id: b571f39b-9f55-4384-9456-78443b7e0388
  symbol: AEM
  side: buy
  qty: '23'
  order_type: limit
  limit_price: '211.07'
  external_id: null
  status: new
- id: 7b565930-fb5c-4edc-9d15-03dcf3a2e25c
  symbol: AEM
  side: buy
  qty: '23'
  order_type: limit
  limit_price: '211.07'
  external_id: null
  status: new
- id: 2a12dc76-f23e-48f6-be0e-2d1f167e2af4
  symbol: GDX
  side: buy
  qty: '49'
  order_type: limit
  limit_price: '100.78'
  external_id: null
  status: new
- id: 5e3cf242-61d7-4223-9dad-f711fae7385f
  symbol: GDX
  side: buy
  qty: '49'
  order_type: limit
  limit_price: '100.78'
  external_id: null
  status: new
- id: d909d18b-a7fa-4440-a74c-6f21ebad653a
  symbol: XLP
  side: buy
  qty: '10'
  order_type: limit
  limit_price: '89.51'
  external_id: null
  status: new
- id: 487ad6c2-eab8-49b1-9883-2ab52a668634
  symbol: XLP
  side: buy
  qty: '35'
  order_type: limit
  limit_price: '89.61'
  external_id: null
  status: new
