strategies:
- id: fbda02e5
  symbol: TSLA
  strategy_type: trailing_stop
  phase: position_open
  quantity: 102
  enabled: true
  entry_type: market
  entry_price: null
  entry_condition: null
  trailing_stop_pct: '0.05'
  take_profit_pct: null
  stop_loss_pct: null
  scale_targets: null
  grid_config: null
  entry_order_id: 5a27e1bf-6614-4ec3-8752-e5946d585192
  entry_fill_price: '424.289216'
  high_watermark: '424.625'
  exit_order_ids: []
  scale_state: null
  grid_state: null
  created_at: '2026-02-10T12:09:34.254479'
  updated_at: '2026-02-10T12:15:21.082529'
  notes: null
- id: 44d67d5b
  symbol: AAPL
  strategy_type: bracket
  phase: position_open
  quantity: 5
  enabled: true
  entry_type: market
  entry_price: null
  entry_condition: null
  trailing_stop_pct: null
  take_profit_pct: '0.03'
  stop_loss_pct: '0.02'
  scale_targets: null
  grid_config: null
  entry_order_id: 583653ba-8164-4e2e-b456-b0523354dc9a
  entry_fill_price: '273.64'
  high_watermark: '273.64'
  exit_order_ids: []
  scale_state: null
  grid_state: null
  created_at: '2026-02-10T12:09:37.448909'
  updated_at: '2026-02-10T12:13:21.084979'
  notes: null
